language: python
python:
- '3.6'
install:
- make develop
script:
- make test
before_deploy:
- make undevelop
deploy:
  provider: pypi
  on:
    tags: true
  user: jessebrennan
  password:
    secure: PjlQMA30KjD/rvhdMonlU01Rb1/sgvZoQcPMnkCkelmsDs1Yv/yWf/GU5MpfglajbJEGimZuQ3EXB3ZhZ4tfs1683nJFK/3XzYDOOcUVbnsTEaGJjSWGxyls0zu9JgI7eMliBtizPUyno9vt9VKQXc9F22u54bDCDn4vvx+gs8Od1vnkS06s89MVZyMGr61Ab1LDprfblZ5NgJmcPRtP59q5aPJqcnKnEeruf1y57sI9duoxvw8HvYz5fE3SL8/vgON+5TBpKiOU/QyA2J1sJKf7SvwJjhd3hZvzN3GDAVobyJ3IHG2VqEd4vPoRJLmWpVPUrJ6RKfGs4algOQGn50g+7KJfo4Ice9Ty9hJYXJqkDbJ0MDUCAFad/S8ZvH3AJdGk7/e3qCUhSD8MT3n8zacCg4neyQ4eGfcG4Vr3RcY9ih60zVDH9KlupKqOYInKSX2Ia8ILvIXDOocJM+g0eG/1eAYXa66itOMhP/QoP6YRgpfasx9H+mvyq0mJaePwW11gOK7t3hvhqdUiAqhhSQvDg61Wjz6hVvAr+4yE8R8as27hQAh0SrJaAiBBWXGLgQBTpTna8Hq87yq/6WQoI5IMF0Q9ucSVQsbRPtoxrTLpTj6M6Q/giapLPrGutMD7xHWzZcQ2PAeVti57Wp8kI0OfmQGhn32hPqfWP8PW3LI=
